source 'https://api.berkshelf.com'

cookbook 'android-sdk', :git => 'https://github.com/gildegoma/chef-android-sdk'
cookbook 'ant', :git => 'https://github.com/opscode-cookbooks/ant.git'
cookbook 'apt', :git => 'https://github.com/opscode-cookbooks/apt.git'
cookbook 'ark', :git => 'https://github.com/opscode-cookbooks/ark.git'
cookbook 'build-essential', :git => 'https://github.com/opscode-cookbooks/build-essential.git'
cookbook 'chef_gem', :git => 'https://github.com/hw-cookbooks/chef_gem.git'
cookbook 'database', :git => 'https://github.com/opscode-cookbooks/database.git'
cookbook 'ddclient', :git => 'https://github.com/freewrite-cookbooks/ddclient.git'
cookbook 'hostsfile', :git => 'https://github.com/customink-webops/hostsfile.git'
cookbook 'iptables', :git => 'https://github.com/opscode-cookbooks/iptables.git'
cookbook 'java', :git => 'https://github.com/tdg5/chef_java.git'
cookbook 'lib', :git => 'https://github.com/freewrite-cookbooks/lib.git'
cookbook 'mysql', :git => 'https://github.com/opscode-cookbooks/mysql.git'
cookbook 'nodejs', :git => 'https://github.com/mdxp/nodejs-cookbook'
cookbook 'npm', :git => 'https://github.com/balbeko/chef-npm.git'
cookbook 'openssh', :git => 'https://github.com/opscode-cookbooks/openssh.git'
cookbook 'openssl', :git => 'https://github.com/opscode-cookbooks/openssl.git'
cookbook 'postgresql', :git => 'https://github.com/freewrite-cookbooks/postgresql.git'
cookbook 'rvm', :git => 'https://github.com/fnichol/chef-rvm.git'
cookbook 'tmux', :git => 'https://github.com/stevendanna/tmux'
cookbook 'vagrant', :git => 'https://github.com/tdg5/vagrant-cookbook.git'
cookbook 'vim', :git => 'https://github.com/opscode-cookbooks/vim.git'
