%w[
  blubuntu-wallpapers
  edgy-community-wallpapers
  edgy-wallpapers
  edubuntu-wallpapers
  feisty-wallpapers
  gnome-backgrounds
  gutsy-wallpapers
  kde-wallpapers
  kdewallpapers
  mate-backgrounds
  peace-wallpapers
  shimmer-wallpapers
  tropic-wallpapers
  ubuntu-gnome-wallpapers
  ubuntu-gnome-wallpapers-trusty
  ubuntukylin-wallpapers
  ubuntukylin-wallpapers-saucy
  ubuntukylin-wallpapers-trusty
  ubuntu-wallpapers
  ubuntu-wallpapers-karmic
  ubuntu-wallpapers-lucid
  ubuntu-wallpapers-maverick
  ubuntu-wallpapers-natty
  ubuntu-wallpapers-oneiric
  ubuntu-wallpapers-precise
  ubuntu-wallpapers-quantal
  ubuntu-wallpapers-raring
  ubuntu-wallpapers-saucy
  ubuntu-wallpapers-trusty
  ubuntustudio-wallpapers
  xubuntu-community-wallpapers
  xubuntu-wallpapers
].each { |pkg| package pkg }
