name 'config'
maintainer 'Danny Guinther'
maintainer_email  'dannyguinther@gmail.com'
license           'MIT'
description       'Various configuration files and tweaks'
long_description  'Various configuration files and tweaks'
version           '0.0.1'

recipe 'config', 'noop'
recipe 'config:git', 'Installs user git config'
recipe 'config:gnome-terminal', 'Installs gnome terminal config'
recipe 'config:irb', 'Installs configuration for Ruby irb'
recipe 'config:sshagent', 'Installs sshagent automatic ssh key loader script'
recipe 'config:vim', 'Installs vim config'

supports 'debian'
supports 'ubuntu'
