#! /bin/sh
### BEGIN INIT INFO
# Provides:          vgaswitcheroo
# Required-Start:    $remote_fs $syslog $all
# Required-Stop:     0 6
# Default-Start:     1 2 3 4 5
# Default-Stop:
# Short-Description: Turn off vgaswitcheroo switch if available
### END INIT INFO


PATH=/sbin:/usr/sbin:/bin:/usr/bin

. /lib/init/vars.sh
. /lib/lsb/init-functions

case "$1" in
	start)
		if [ -e /sys/kernel/debug/vgaswitcheroo/switch ]; then
			echo OFF > /sys/kernel/debug/vgaswitcheroo/switch
		fi
	;;
	restart|reload|force-reload)
		echo "Error: argument '$1' not supported" >&2
		exit 3
	;;
	stop)
	;;
	*)
		echo "Usage: $0 start|stop" >&2
		exit 3
	;;
esac
