#! /bin/sh
### BEGIN INIT INFO
# Provides:          powertune
# Required-Start:    $remote_fs $syslog $all
# Required-Stop:     0 6
# Default-Start:     1 2 3 4 5
# Default-Stop:
# Short-Description: Sets optimal power management configuration
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin

. /lib/init/vars.sh
. /lib/lsb/init-functions

case "$1" in
  force-reload|reload|restart|start)
    # VM writeback timeout
    echo '1500' > '/proc/sys/vm/dirty_writeback_centisecs';

    # Enable SATA link power Managmenet for host0
    echo 'min_power' > '/sys/class/scsi_host/host0/link_power_management_policy';

    # Enable SATA link power Managmenet for host1
    echo 'min_power' > '/sys/class/scsi_host/host1/link_power_management_policy';

    # Enable SATA link power Managmenet for host2
    echo 'min_power' > '/sys/class/scsi_host/host2/link_power_management_policy';

    # Enable SATA link power Managmenet for host3
    echo 'min_power' > '/sys/class/scsi_host/host3/link_power_management_policy';

    # Enable SATA link power Managmenet for host4
    echo 'min_power' > '/sys/class/scsi_host/host4/link_power_management_policy';

    # Enable SATA link power Managmenet for host5
    echo 'min_power' > '/sys/class/scsi_host/host5/link_power_management_policy';

    # Enable Audio codec power management
    echo '1' > '/sys/module/snd_hda_intel/parameters/power_save';

    # NMI watchdog should be turned off
    echo '0' > '/proc/sys/kernel/nmi_watchdog';

    # Autosuspend for USB device Atmel maXTouch Digitizer [Atmel] (touchscreen)
    echo 'auto' > '/sys/bus/usb/devices/2-1.6/power/control';

    # Autosuspend for USB device SAM [MICROSOFT]
    echo 'auto' > '/sys/bus/usb/devices/2-1.5/power/control';

    # Causes keyboard to sleep and never awaken. Also seems to hang shut down.
    # Autosuspend for USB device Bluetooth and Wireless LAN Composite Device [Marvell]
    #echo 'auto' > '/sys/bus/usb/devices/3-3/power/control';

    # Runtime PM for PCI Device Intel Corporation 7 Series/C210 Series Chipset Family USB xHCI Host Controller
    echo 'auto' > '/sys/bus/pci/devices/0000:00:14.0/power/control';

    # Runtime PM for PCI Device Intel Corporation 3rd Gen Core processor Graphics Controller
    echo 'auto' > '/sys/bus/pci/devices/0000:00:02.0/power/control';

    # Runtime PM for PCI Device Intel Corporation 7 Series/C210 Series Chipset Family USB Enhanced Host Controller #1
    echo 'auto' > '/sys/bus/pci/devices/0000:00:1d.0/power/control';

    # Runtime PM for PCI Device Intel Corporation 3rd Gen Core processor DRAM Controller
    echo 'auto' > '/sys/bus/pci/devices/0000:00:00.0/power/control';

    # Runtime PM for PCI Device Intel Corporation 7 Series/C210 Series Chipset Family USB Enhanced Host Controller #2
    echo 'auto' > '/sys/bus/pci/devices/0000:00:1a.0/power/control';

    # Runtime PM for PCI Device Intel Corporation 7 Series/C210 Series Chipset Family MEI Controller #1
    echo 'auto' > '/sys/bus/pci/devices/0000:00:16.0/power/control';

    # Runtime PM for PCI Device Intel Corporation 7 Series/C210 Series Chipset Family SMBus Controller
    echo 'auto' > '/sys/bus/pci/devices/0000:00:1f.3/power/control';

    # Runtime PM for PCI Device Intel Corporation 7 Series/C210 Series Chipset Family High Definition Audio Controller
    echo 'auto' > '/sys/bus/pci/devices/0000:00:1b.0/power/control';

    # Runtime PM for PCI Device Intel Corporation HM77 Express Chipset LPC Controller
    echo 'auto' > '/sys/bus/pci/devices/0000:00:1f.0/power/control';

    # Runtime PM for PCI Device Intel Corporation 7 Series Chipset Family 6-port SATA Controller [AHCI mode]
    echo 'auto' > '/sys/bus/pci/devices/0000:00:1f.2/power/control';

    # Using 'ondemand' cpufreq governor
    /sbin/modprobe cpufreq_ondemand > /dev/null 2>&1
    echo 'ondemand' > '/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor';
    echo 'ondemand' > '/sys/devices/system/cpu/cpu1/cpufreq/scaling_governor';
    echo 'ondemand' > '/sys/devices/system/cpu/cpu2/cpufreq/scaling_governor';
    echo 'ondemand' > '/sys/devices/system/cpu/cpu3/cpufreq/scaling_governor';
  ;;
  stop)
    echo "Warning: Stop action is noop."
    exit 0
  ;;
  *)
    echo "Usage: $0 force-reload|reload|restart|start|stop" >&2
    exit 3
  ;;
esac
