#! ruby

require 'open-uri'
raise "No gem name given" if ARGV.size == 0

ARGV.each do |gem|
  json = open("https://rubygems.org/api/v1/gems/#{gem}.json").read
  uri = json[/[^"]+github.com[^"]+/]

  unless uri
    puts "Could not find github homepage for #{gem}, heading to RubyGems instead"
    uri = "https://rubygems.org/gems/#{gem}"
  end

  exec "web #{uri}"
end
